// Generated by tools/build-audio.mjs. Do not edit.
/** Where each footfall sits in the sprite, in seconds. */
export const FOOTSTEPS = [
  {
    "offset": 0,
    "duration": 0.352
  },
  {
    "offset": 0.352,
    "duration": 0.352
  },
  {
    "offset": 0.704,
    "duration": 0.352
  },
  {
    "offset": 1.056,
    "duration": 0.352
  },
  {
    "offset": 1.408,
    "duration": 0.352
  },
  {
    "offset": 1.76,
    "duration": 0.352
  },
  {
    "offset": 2.112,
    "duration": 0.352
  },
  {
    "offset": 2.464,
    "duration": 0.352
  }
] as const;
