// Generated by tools/write-manifest.mjs. Do not edit.
// Measured from the built prop libraries, so a collider can never
// disagree with the mesh it stands for.
import type { Vec3 } from "../types";

export const PROP_SIZES = {
  "bed": [1.972, 0.9351, 1.1518],
  "chair": [0.3531, 0.85, 0.4189],
  "chandelier": [0.7357, 0.6228, 0.7299],
  "desk": [1.5512, 0.6999, 0.9117],
  "nightstand": [0.7858, 0.8274, 0.5609],
  "rug": [3.5911, 0.0167, 2.2338],
  "telephone": [0.3821, 0.1398, 0.2399],
  "wardrobe": [0.8329, 1.8495, 0.4166],
  "window": [2.0017, 1.2304, 0.2219],
} as const satisfies Record<string, Vec3>;

export type PropId = keyof typeof PROP_SIZES;
