// Generated by tools/write-manifest.mjs. Do not edit.
// Measured from the built prop libraries, so a collider can never
// disagree with the mesh it stands for.
import type { Vec3 } from "../types";

export const PROP_SIZES = {
  "armchair": [0.9173, 1.8086, 1.0954],
  "bed": [1.2807, 1.3036, 2.0806],
  "chair": [0.5873, 1.1569, 0.5511],
  "chandelier": [0.7357, 0.6228, 0.7299],
  "couch": [2.8937, 1.6898, 2.2003],
  "crate": [0.433, 0.1513, 0.2694],
  "desk": [1.9599, 1.0059, 1.0854],
  "dresser": [1.3913, 1.5104, 0.6183],
  "painting-large": [1.2184, 1.4626, 0.1164],
  "painting-small": [2.0014, 1.1645, 0.02],
  "painting-square": [0.1363, 0.8544, 0.7128],
  "rug": [3.5911, 0.0167, 2.2338],
  "sideboard": [1.2189, 0.8985, 2],
  "wardrobe": [1.0941, 2.0739, 0.5603],
  "workbench": [1.9498, 0.8317, 0.7017],
} as const satisfies Record<string, Vec3>;

export type PropId = keyof typeof PROP_SIZES;
